using Pix3.Rooms.Protocol;

namespace Pix3.Rooms.Tests.Protocol;

/// <summary>
/// Byte-exact golden vectors for the hot plane (TypeIds 67 / 68 / 69 / 130).
/// </summary>
/// <remarks>
/// <para>
/// <b>Every expected byte string in this file was written out by hand from the offset tables in
/// <c>docs/protocol.md</c>, never captured from a run of the codec.</b> That is the whole point: a
/// vector generated by the code under test proves only that the code agrees with itself, while these
/// fail the moment an offset, a width or an endianness drifts away from the published contract — which
/// is the contract the hand-written TypeScript client codecs are also written against.
/// </para>
/// <para>
/// One sample entity is reused throughout, chosen so that every field is asymmetric: no two fields
/// share a value, every multi-byte field has distinguishable high and low bytes (so a swapped
/// endianness cannot pass), and the velocities cover both signs.
/// </para>
/// </remarks>
public class HotWireGoldenVectorTests
{
    /// <summary>Slot 7, generation 2 — <c>slot | (generation &lt;&lt; 16)</c> per the NetId section.</summary>
    private const uint SampleNetId = 0x0002_0007;

    /// <summary>
    /// The entity every record vector below describes. Hand-encoded field by field:
    /// Kind <c>0x1234</c>, OwnerId 42 (<c>0x2A</c>), QX <c>0x89AB</c>, QY <c>0x0100</c>,
    /// QRot <c>0x40</c>, QVx −1000 (<c>0xFC18</c> two's complement), QVy 32767 (<c>0x7FFF</c>),
    /// Flags <c>0xA9</c> = <c>1010_1001</c>: policy bits 0–1 = <c>01</c> (Shared), the fabric's
    /// reserved bit 2 clear as required, app bits 3–7 = <c>10101</c>.
    /// </summary>
    private static EntityWireState SampleState() => new()
    {
        Kind = 0x1234,
        OwnerId = 42,
        QX = 0x89AB,
        QY = 0x0100,
        QRot = 0x40,
        QVx = -1000,
        QVy = short.MaxValue,
        Flags = 0xA9,
    };

    /// <summary>
    /// The 20-byte <c>FullRecord</c> for <see cref="SampleState"/>, spelled out per the offset table:
    /// <c>0 u32 NetId · 4 u16 Kind · 6 u32 OwnerId · 10 u16 QX · 12 u16 QY · 14 u8 QRot ·
    /// 15 i16 QVx · 17 i16 QVy · 19 u8 Flags</c>, all little-endian.
    /// </summary>
    private const string SampleFullRecordHex = "07000200 3412 2A000000 AB89 0001 40 18FC FF7F A9";

    private static byte[] Hex(string hex)
        => Convert.FromHexString(hex.Replace(" ", "").Replace("|", "").Replace("\n", "").Replace("\r", ""));

    // ── FullRecord ────────────────────────────────────────────────────────────

    [Fact]
    public void FullRecord_matches_its_hand_derived_20_bytes()
    {
        byte[] buffer = new byte[HotWire.FullRecordSize];

        int written = HotWire.WriteFullRecord(buffer, SampleNetId, SampleState());

        Assert.Equal(20, written);
        Assert.Equal(Hex(SampleFullRecordHex), buffer);
    }

    [Fact]
    public void FullRecord_decodes_back_to_every_field_it_encoded()
    {
        Assert.True(HotWire.TryReadFullRecord(Hex(SampleFullRecordHex), out uint netId, out EntityWireState state));

        Assert.Equal(SampleNetId, netId);
        Assert.Equal(0x1234, state.Kind);
        Assert.Equal(42u, state.OwnerId);
        Assert.Equal(0x89AB, state.QX);
        Assert.Equal(0x0100, state.QY);
        Assert.Equal(0x40, state.QRot);
        Assert.Equal(-1000, state.QVx);
        Assert.Equal(short.MaxValue, state.QVy);
        Assert.Equal(0xA9, state.Flags);
    }

    [Fact]
    public void FullRecord_writer_refuses_a_short_destination_without_writing_anything()
    {
        byte[] buffer = new byte[HotWire.FullRecordSize - 1];

        Assert.Equal(0, HotWire.WriteFullRecord(buffer, SampleNetId, SampleState()));
        Assert.All(buffer, b => Assert.Equal(0, b));
        Assert.False(HotWire.TryReadFullRecord(buffer, out _, out _));
    }

    // ── UpdateRecord (S→C, slot-addressed) ────────────────────────────────────

    [Fact]
    public void UpdateRecord_with_the_typical_moving_entity_mask_is_eight_bytes()
    {
        // "A typical moving entity costs 8 B (u16 Slot + mask + QX + QY + QRot)" — protocol.md.
        const byte mask = DeltaMask.X | DeltaMask.Y | DeltaMask.Rot;   // 0x07
        byte[] buffer = new byte[HotWire.MaxUpdateRecordSize];

        int written = HotWire.WriteUpdateRecord(buffer, slot: 0x0102, mask, SampleState());

        Assert.Equal(8, written);
        Assert.Equal(Hex("0201 07 AB89 0001 40"), buffer.AsSpan(0, written).ToArray());
    }

    [Fact]
    public void UpdateRecord_with_every_field_is_the_thirteen_byte_maximum_in_bit_order()
    {
        // 0x3F | 0x80: every payload bit plus Teleport, which contributes no bytes.
        const byte mask = DeltaMask.PayloadBits | DeltaMask.Teleport;   // 0xBF
        byte[] buffer = new byte[HotWire.MaxUpdateRecordSize];

        int written = HotWire.WriteUpdateRecord(buffer, slot: 0xFFFF, mask, SampleState());

        Assert.Equal(13, written);
        Assert.Equal(Hex("FFFF BF AB89 0001 40 18FC FF7F A9"), buffer.AsSpan(0, written).ToArray());
    }

    [Fact]
    public void UpdateRecord_carrying_only_signal_bits_is_a_bare_three_byte_header()
    {
        const byte mask = DeltaMask.ColdDirty | DeltaMask.Teleport;   // 0xC0, no payload bytes
        byte[] buffer = new byte[HotWire.MaxUpdateRecordSize];

        int written = HotWire.WriteUpdateRecord(buffer, slot: 0x0003, mask, SampleState());

        Assert.Equal(3, written);
        Assert.Equal(Hex("0300 C0"), buffer.AsSpan(0, written).ToArray());
    }

    [Fact]
    public void UpdateRecord_reader_leaves_unmasked_fields_untouched()
    {
        // Rot + Flags only (0x24): a decoder that mis-ordered the fields would land QRot on Flags.
        Assert.True(
            HotWire.TryReadUpdateRecord(
                Hex("0201 24 40 A9"),
                out ushort slot,
                out byte mask,
                out EntityWireState state,
                out int bytesRead));

        Assert.Equal(0x0102, slot);
        Assert.Equal(0x24, mask);
        Assert.Equal(5, bytesRead);
        Assert.Equal(0x40, state.QRot);
        Assert.Equal(0xA9, state.Flags);
        Assert.Equal(0, state.QX);
        Assert.Equal(0, state.QY);
    }

    [Fact]
    public void UpdateRecord_reader_refuses_a_record_truncated_inside_its_masked_payload()
    {
        // Mask 0x07 promises 5 payload bytes; only 4 follow.
        Assert.False(HotWire.TryReadUpdateRecord(Hex("0201 07 AB89 0001"), out _, out _, out _, out int bytesRead));
        Assert.Equal(0, bytesRead);
    }

    // ── OwnerUpdateRecord (C→S, netId-addressed) ──────────────────────────────

    [Fact]
    public void OwnerUpdateRecord_is_keyed_by_netId_and_five_bytes_of_header()
    {
        const byte mask = DeltaMask.X | DeltaMask.Y;   // 0x03
        byte[] buffer = new byte[HotWire.MaxOwnerUpdateRecordSize];

        int written = HotWire.WriteOwnerUpdateRecord(buffer, SampleNetId, mask, SampleState());

        Assert.Equal(9, written);
        Assert.Equal(Hex("07000200 03 AB89 0001"), buffer.AsSpan(0, written).ToArray());
    }

    [Fact]
    public void OwnerUpdateRecord_maximum_is_fifteen_bytes()
    {
        byte[] buffer = new byte[HotWire.MaxOwnerUpdateRecordSize];

        int written = HotWire.WriteOwnerUpdateRecord(buffer, SampleNetId, DeltaMask.PayloadBits, SampleState());

        Assert.Equal(15, written);
        Assert.Equal(Hex("07000200 3F AB89 0001 40 18FC FF7F A9"), buffer.AsSpan(0, written).ToArray());
    }

    // ── Removal record ────────────────────────────────────────────────────────

    [Fact]
    public void Removal_record_is_a_bare_little_endian_slot()
    {
        byte[] buffer = new byte[HotWire.RemovedSlotSize];

        Assert.Equal(2, HotWire.WriteRemovedSlot(buffer, 0x0102));
        Assert.Equal(Hex("0201"), buffer);
    }

    // ── SnapshotPacket (68) ───────────────────────────────────────────────────

    [Fact]
    public void SnapshotPacket_with_one_record_matches_its_hand_derived_frame()
    {
        byte[] frame = new byte[HotWire.SnapshotPacketHeaderSize + HotWire.FullRecordSize];

        int offset = HotWire.WriteSnapshotPacketHeader(frame, seq: 0x0102, serverTick: 1234);
        offset += HotWire.WriteFullRecord(frame.AsSpan(offset), SampleNetId, SampleState());
        Assert.True(HotWire.TryPatchSnapshotPacketCount(frame, 1));
        Assert.True(HotWire.TryPatchSnapshotPacketFrameFlags(frame, FrameFlags.Final));

        Assert.Equal(30, offset);
        // 0 u8 68=0x44 · 1 u16 Seq · 3 u32 ServerTick (1234 = 0x4D2) · 7 u8 FrameFlags=Final · 8 u16 Count
        Assert.Equal(Hex("44 0201 D2040000 01 0100 " + SampleFullRecordHex), frame);
    }

    [Fact]
    public void Empty_final_SnapshotPacket_is_ten_bytes_and_still_carries_Final()
    {
        // "A snapshot is always sent, even when it is empty" — a joiner who can see nothing must still
        // be told the snapshot is complete.
        byte[] frame = new byte[HotWire.SnapshotPacketHeaderSize];

        HotWire.WriteSnapshotPacketHeader(frame, seq: 0, serverTick: 0);
        Assert.True(HotWire.TryPatchSnapshotPacketFrameFlags(frame, FrameFlags.Final));

        Assert.Equal(Hex("44 0000 00000000 01 0000"), frame);
        Assert.True(HotWire.TryReadSnapshotPacket(frame, out _, out _, out byte flags, out int count, out _));
        Assert.Equal(0, count);
        Assert.True(FrameFlags.IsFinal(flags));
    }

    [Fact]
    public void SnapshotPacket_reader_refuses_a_count_the_buffer_cannot_hold()
    {
        // Header claims two records; only one follows.
        byte[] frame = Hex("44 0201 D2040000 01 0200 " + SampleFullRecordHex);

        Assert.False(HotWire.TryReadSnapshotPacket(frame, out _, out _, out _, out _, out _));
    }

    [Fact]
    public void SnapshotPacket_reader_refuses_a_frame_carrying_another_TypeId()
    {
        byte[] frame = Hex("45 0201 D2040000 01 0000");

        Assert.False(HotWire.TryReadSnapshotPacket(frame, out _, out _, out _, out _, out _));
    }

    // ── DeltaPacket (69) ──────────────────────────────────────────────────────

    [Fact]
    public void Empty_DeltaPacket_is_thirteen_bytes_with_all_three_counts_present()
    {
        byte[] frame = new byte[HotWire.DeltaPacketFixedOverhead];

        int offset = HotWire.WriteDeltaPacketHeader(frame, seq: 0x0102, serverTick: 1234);
        offset += HotWire.WriteSectionCountPlaceholder(frame.AsSpan(offset));
        offset += HotWire.WriteSectionCountPlaceholder(frame.AsSpan(offset));
        offset += HotWire.WriteSectionCountPlaceholder(frame.AsSpan(offset));

        Assert.Equal(13, offset);
        Assert.Equal(Hex("45 0201 D2040000 0000 0000 0000"), frame);
    }

    [Fact]
    public void DeltaPacket_interleaves_removals_then_enters_then_updates()
    {
        // 7 header + (2 count + 2 slot) + (2 count + 20 full) + (2 count + 8 update) = 43.
        byte[] frame = new byte[43];

        int offset = HotWire.WriteDeltaPacketHeader(frame, seq: 0x0102, serverTick: 1234);

        int removedCountOffset = offset;
        offset += HotWire.WriteSectionCountPlaceholder(frame.AsSpan(offset));
        offset += HotWire.WriteRemovedSlot(frame.AsSpan(offset), 0x0003);
        Assert.True(HotWire.TryPatchSectionCount(frame, removedCountOffset, 1));

        int enterCountOffset = offset;
        offset += HotWire.WriteSectionCountPlaceholder(frame.AsSpan(offset));
        offset += HotWire.WriteFullRecord(frame.AsSpan(offset), SampleNetId, SampleState());
        Assert.True(HotWire.TryPatchSectionCount(frame, enterCountOffset, 1));

        int updateCountOffset = offset;
        offset += HotWire.WriteSectionCountPlaceholder(frame.AsSpan(offset));
        offset += HotWire.WriteUpdateRecord(
            frame.AsSpan(offset),
            slot: 0x0102,
            DeltaMask.X | DeltaMask.Y | DeltaMask.Rot,
            SampleState());
        Assert.True(HotWire.TryPatchSectionCount(frame, updateCountOffset, 1));

        Assert.Equal(43, offset);
        Assert.Equal(7, removedCountOffset);
        Assert.Equal(11, enterCountOffset);
        Assert.Equal(33, updateCountOffset);
        Assert.Equal(
            Hex("45 0201 D2040000 0100 0300 0100 " + SampleFullRecordHex + " 0100 0201 07 AB89 0001 40"),
            frame);
    }

    [Fact]
    public void DeltaPacket_reader_splits_the_hand_written_frame_into_its_three_sections()
    {
        byte[] frame = Hex(
            "45 0201 D2040000 0100 0300 0100 " + SampleFullRecordHex + " 0100 0201 07 AB89 0001 40");

        Assert.True(HotWire.TryReadDeltaPacket(frame, out DeltaPacketSections sections));

        Assert.Equal(0x0102, sections.Seq);
        Assert.Equal(1234u, sections.ServerTick);

        Assert.Equal(1, sections.RemovedCount);
        Assert.True(sections.TryGetRemovedSlot(0, out ushort removedSlot));
        Assert.Equal(0x0003, removedSlot);

        Assert.Equal(1, sections.EnterCount);
        Assert.True(sections.TryGetEnterRecord(0, out uint netId, out EntityWireState entered));
        Assert.Equal(SampleNetId, netId);
        Assert.Equal(0x89AB, entered.QX);

        Assert.Equal(1, sections.UpdateCount);
        int cursor = 0;
        Assert.True(sections.TryReadNextUpdate(ref cursor, out ushort slot, out byte mask, out EntityWireState updated));
        Assert.Equal(0x0102, slot);
        Assert.Equal(0x07, mask);
        Assert.Equal(0x0100, updated.QY);
        Assert.Equal(8, cursor);
    }

    [Fact]
    public void DeltaPacket_reader_refuses_a_frame_shorter_than_its_fixed_overhead()
    {
        Assert.False(HotWire.TryReadDeltaPacket(Hex("45 0201 D2040000 0000 0000 00"), out _));
    }

    // ── EntityUpdatePacket (67, C→S) ──────────────────────────────────────────

    [Fact]
    public void EntityUpdatePacket_matches_its_hand_derived_frame()
    {
        byte[] frame = new byte[15];

        int offset = HotWire.WriteEntityUpdatePacketHeader(frame, clientTick: 1234);
        offset += HotWire.WriteOwnerUpdateRecord(
            frame.AsSpan(offset),
            SampleNetId,
            DeltaMask.X | DeltaMask.Y,
            SampleState());
        Assert.True(HotWire.TryPatchEntityUpdatePacketCount(frame, 1));

        Assert.Equal(15, offset);
        // 0 u8 67=0x43 · 1 u32 ClientTick · 5 u8 Count · 6 OwnerUpdateRecord
        Assert.Equal(Hex("43 D2040000 01 07000200 03 AB89 0001"), frame);
    }

    [Fact]
    public void EntityUpdatePacket_reader_refuses_a_count_that_cannot_fit_its_minimum_records()
    {
        // Count 3 needs at least 15 bytes of records; 9 are present.
        Assert.False(HotWire.TryReadEntityUpdatePacket(Hex("43 D2040000 03 07000200 03 AB89 0001"), out _, out _, out _));
    }

    // ── SignalBatchPacket (130) ───────────────────────────────────────────────

    [Fact]
    public void SignalBatchPacket_matches_its_hand_derived_frame()
    {
        // Entry = 6 + NameLength + PayloadLength: "fire"/2 = 12 B, "hit"/0 = 9 B, header 8 B → 29 B.
        byte[] frame = new byte[29];
        byte[] fire = "fire"u8.ToArray();
        byte[] hit = "hit"u8.ToArray();

        int offset = HotWire.WriteSignalBatchPacketHeader(frame, seq: 0x0102, serverTick: 1234);
        offset += HotWire.WriteSignalEntry(frame.AsSpan(offset), 42, fire, [0xAA, 0xBB]);
        offset += HotWire.WriteSignalEntry(frame.AsSpan(offset), 7, hit, []);
        Assert.True(HotWire.TryPatchSignalBatchPacketCount(frame, 2));

        Assert.Equal(29, offset);
        // 0 u8 130=0x82 · 1 u16 Seq · 3 u32 ServerTick · 7 u8 Count, then
        // (u32 Sender, u8 NameLength, name, u8 PayloadLength, payload) per entry.
        // "fire" = 66 69 72 65, "hit" = 68 69 74 in UTF-8.
        Assert.Equal(
            Hex("82 0201 D2040000 02 2A000000 04 66697265 02 AABB 07000000 03 686974 00"),
            frame);
    }

    [Fact]
    public void SignalBatchPacket_reader_walks_both_hand_written_entries()
    {
        byte[] frame = Hex("82 0201 D2040000 02 2A000000 04 66697265 02 AABB 07000000 03 686974 00");

        Assert.True(HotWire.TryReadSignalBatchPacket(frame, out SignalBatchSections sections));
        Assert.Equal(2, sections.Count);

        int cursor = 0;
        Assert.True(sections.TryReadNextEntry(ref cursor, out uint sender, out ReadOnlySpan<byte> name, out ReadOnlySpan<byte> payload));
        Assert.Equal(42u, sender);
        Assert.Equal("fire", System.Text.Encoding.UTF8.GetString(name));
        Assert.Equal(new byte[] { 0xAA, 0xBB }, payload.ToArray());
        Assert.Equal(12, cursor);

        Assert.True(sections.TryReadNextEntry(ref cursor, out sender, out name, out payload));
        Assert.Equal(7u, sender);
        Assert.Equal("hit", System.Text.Encoding.UTF8.GetString(name));
        Assert.Equal(0, payload.Length);
        Assert.Equal(29 - HotWire.SignalBatchPacketHeaderSize, cursor);

        Assert.False(sections.TryReadNextEntry(ref cursor, out _, out _, out _));
    }

    [Fact]
    public void Signal_entry_writer_refuses_an_empty_name_and_an_oversized_payload()
    {
        byte[] buffer = new byte[512];

        Assert.Equal(0, HotWire.WriteSignalEntry(buffer, 42, [], [0x01]));
        Assert.Equal(0, HotWire.WriteSignalEntry(buffer, 42, new byte[HotWire.MaxSignalNameLength + 1], []));
        Assert.Equal(0, HotWire.WriteSignalEntry(buffer, 42, "n"u8, new byte[HotWire.MaxSignalPayloadLength + 1]));
    }

    [Fact]
    public void Signal_entry_reader_refuses_a_zero_name_length()
    {
        Assert.False(HotWire.TryReadSignalEntry(Hex("2A000000 00 00 0000"), out _, out _, out _, out _));
    }

    // ── Geometry constants, straight out of the spec's offset tables ──────────

    [Theory]
    [InlineData(0x00, 0)]                  // no fields
    [InlineData(DeltaMask.X, 2)]
    [InlineData(DeltaMask.Y, 2)]
    [InlineData(DeltaMask.Rot, 1)]
    [InlineData(DeltaMask.Vx, 2)]
    [InlineData(DeltaMask.Vy, 2)]
    [InlineData(DeltaMask.Flags, 1)]
    [InlineData(DeltaMask.ColdDirty, 0)]   // signal bit: no bytes
    [InlineData(DeltaMask.Teleport, 0)]    // signal bit: no bytes
    [InlineData(0x07, 5)]                  // X + Y + Rot — the typical moving entity
    [InlineData(0x3F, 10)]                 // every payload field
    [InlineData(0xFF, 10)]                 // payload fields plus both signal bits
    public void Masked_payload_sizes_match_the_delta_mask_table(int mask, int expectedBytes)
    {
        Assert.Equal(expectedBytes, DeltaMask.PayloadSize((byte)mask));
        Assert.Equal(expectedBytes + 3, HotWire.UpdateRecordSize((byte)mask));
        Assert.Equal(expectedBytes + 5, HotWire.OwnerUpdateRecordSize((byte)mask));
    }

    [Fact]
    public void Packet_geometry_constants_match_the_spec_tables()
    {
        Assert.Equal(20, HotWire.FullRecordSize);
        Assert.Equal(2, HotWire.RemovedSlotSize);
        Assert.Equal(3, HotWire.MinUpdateRecordSize);
        Assert.Equal(13, HotWire.MaxUpdateRecordSize);
        Assert.Equal(5, HotWire.MinOwnerUpdateRecordSize);
        Assert.Equal(15, HotWire.MaxOwnerUpdateRecordSize);
        Assert.Equal(10, HotWire.SnapshotPacketHeaderSize);
        Assert.Equal(7, HotWire.SnapshotPacketFrameFlagsOffset);
        Assert.Equal(8, HotWire.SnapshotPacketCountOffset);
        Assert.Equal(7, HotWire.DeltaPacketHeaderSize);
        Assert.Equal(13, HotWire.DeltaPacketFixedOverhead);
        Assert.Equal(6, HotWire.EntityUpdatePacketHeaderSize);
        Assert.Equal(8, HotWire.SignalBatchPacketHeaderSize);
        Assert.Equal(6, HotWire.SignalEntryOverheadSize);
        Assert.Equal(64, HotWire.MaxSignalNameLength);
        Assert.Equal(255, HotWire.MaxSignalPayloadLength);
    }

    [Fact]
    public void Client_masks_are_limited_to_the_payload_bits_plus_Teleport()
    {
        Assert.Equal(0xBF, HotWire.ClientAllowedMaskBits);
        Assert.Equal(0x40, HotWire.ClientForbiddenMaskBits);

        Assert.True(HotWire.IsClientMaskLegal(0x00));
        Assert.True(HotWire.IsClientMaskLegal(0x3F));
        Assert.True(HotWire.IsClientMaskLegal(0xBF));

        // ColdDirty is server-authored: it promises a follow-up EntityPropsChangedEvent.
        Assert.False(HotWire.IsClientMaskLegal(DeltaMask.ColdDirty));
        Assert.False(HotWire.IsClientMaskLegal(0xFF));
    }
}
